import { Game } from '@/lib/models/game.model'

export const GAME_VERSIONS: Game[] = [
  {
    label: 'Red',
    value: 'red',
    group: 'red-blue',
    generation: 'Generation I',
    genValue: 'generation-i',
    genGroups: ['red-blue', 'yellow'],
    moveGroups: ['red-blue', 'yellow'],
  },
  {
    label: 'Blue',
    value: 'blue',
    group: 'red-blue',
    generation: 'Generation I',
    genValue: 'generation-i',
    genGroups: ['red-blue', 'yellow'],
    moveGroups: ['red-blue', 'yellow'],
  },
  {
    label: 'Yellow',
    value: 'yellow',
    group: 'yellow',
    generation: 'Generation I',
    genValue: 'generation-i',
    genGroups: ['red-blue', 'yellow'],
    moveGroups: ['red-blue', 'yellow'],
  },
  {
    label: 'Gold',
    value: 'gold',
    group: 'gold-silver',
    generation: 'Generation II',
    genValue: 'generation-ii',
    genGroups: ['gold-silver', 'crystal'],
    moveGroups: ['gold-silver', 'crystal'],
  },
  {
    label: 'Silver',
    value: 'silver',
    group: 'gold-silver',
    generation: 'Generation II',
    genValue: 'generation-ii',
    genGroups: ['gold-silver', 'crystal'],
    moveGroups: ['gold-silver', 'crystal'],
  },
  {
    label: 'Crystal',
    value: 'crystal',
    group: 'crystal',
    generation: 'Generation II',
    genValue: 'generation-ii',
    genGroups: ['gold-silver', 'crystal'],
    moveGroups: ['gold-silver', 'crystal'],
  },
  {
    label: 'Ruby',
    value: 'ruby',
    group: 'ruby-sapphire',
    generation: 'Generation III',
    genValue: 'generation-iii',
    genGroups: ['ruby-sapphire', 'emerald'],
    moveGroups: ['ruby-sapphire', 'emerald', 'firered-leafgreen'],
  },
  {
    label: 'Sapphire',
    value: 'sapphire',
    group: 'ruby-sapphire',
    generation: 'Generation III',
    genValue: 'generation-iii',
    genGroups: ['ruby-sapphire', 'emerald'],
    moveGroups: ['ruby-sapphire', 'emerald', 'firered-leafgreen'],
  },
  {
    label: 'Emerald',
    value: 'emerald',
    group: 'emerald',
    generation: 'Generation III',
    genValue: 'generation-iii',
    genGroups: ['ruby-sapphire', 'emerald'],
    moveGroups: ['ruby-sapphire', 'emerald', 'firered-leafgreen'],
  },
  {
    label: 'Fire Red',
    value: 'firered',
    group: 'firered-leafgreen',
    generation: 'Generation III',
    genValue: 'generation-iii',
    genGroups: ['firered-leafgreen'],
    moveGroups: ['ruby-sapphire', 'emerald', 'firered-leafgreen'],
  },
  {
    label: 'Leaf Green',
    value: 'leafgreen',
    group: 'firered-leafgreen',
    generation: 'Generation III',
    genValue: 'generation-iii',
    genGroups: ['firered-leafgreen'],
    moveGroups: ['ruby-sapphire', 'emerald', 'firered-leafgreen'],
  },
  {
    label: 'Diamond',
    value: 'diamond',
    group: 'diamond-pearl',
    generation: 'Generation IV',
    genValue: 'generation-iv',
    genGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
    moveGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
  },
  {
    label: 'Pearl',
    value: 'pearl',
    group: 'diamond-pearl',
    generation: 'Generation IV',
    genValue: 'generation-iv',
    genGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
    moveGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
  },
  {
    label: 'Platinum',
    value: 'platinum',
    group: 'platinum',
    generation: 'Generation IV',
    genValue: 'generation-iv',
    genGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
    moveGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
  },
  {
    label: 'Heart Gold',
    value: 'heartgold',
    group: 'heartgold-soulsilver',
    generation: 'Generation IV',
    genValue: 'generation-iv',
    genGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
    moveGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
  },
  {
    label: 'Soul Silver',
    value: 'soulsilver',
    group: 'heartgold-soulsilver',
    generation: 'Generation IV',
    genValue: 'generation-iv',
    genGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
    moveGroups: ['diamond-pearl', 'platinum', 'heartgold-soulsilver'],
  },
  {
    label: 'Black',
    value: 'black',
    group: 'black-white',
    generation: 'Generation V',
    genValue: 'generation-v',
    genGroups: ['black-white', 'black-2-white-2'],
    moveGroups: ['black-white', 'black-2-white-2'],
  },
  {
    label: 'White',
    value: 'white',
    group: 'black-white',
    generation: 'Generation V',
    genValue: 'generation-v',
    genGroups: ['black-white', 'black-2-white-2'],
    moveGroups: ['black-white', 'black-2-white-2'],
  },
  {
    label: 'Black 2',
    value: 'black-2',
    group: 'black-2-white-2',
    generation: 'Generation V',
    genValue: 'generation-v',
    genGroups: ['black-white', 'black-2-white-2'],
    moveGroups: ['black-white', 'black-2-white-2'],
  },
  {
    label: 'White 2',
    value: 'white-2',
    group: 'black-2-white-2',
    generation: 'Generation V',
    genValue: 'generation-v',
    genGroups: ['black-white', 'black-2-white-2'],
    moveGroups: ['black-white', 'black-2-white-2'],
  },
  {
    label: 'X',
    value: 'x',
    group: 'x-y',
    generation: 'Generation VI',
    genValue: 'generation-vi',
    genGroups: ['x-y', 'omega-ruby-alpha-sapphire'],
    moveGroups: ['x-y', 'omega-ruby-alpha-sapphire'],
  },
  {
    label: 'Y',
    value: 'y',
    group: 'x-y',
    generation: 'Generation VI',
    genValue: 'generation-vi',
    genGroups: ['x-y', 'omega-ruby-alpha-sapphire'],
    moveGroups: ['x-y', 'omega-ruby-alpha-sapphire'],
  },
  {
    label: 'Omega Ruby',
    value: 'omega-ruby',
    group: 'omega-ruby-alpha-sapphire',
    generation: 'Generation VI',
    genValue: 'generation-vi',
    genGroups: ['x-y', 'omega-ruby-alpha-sapphire'],
    moveGroups: ['x-y', 'omega-ruby-alpha-sapphire'],
  },
  {
    label: 'Alpha Sapphire',
    value: 'alpha-sapphire',
    group: 'omega-ruby-alpha-sapphire',
    generation: 'Generation VI',
    genValue: 'generation-vi',
    genGroups: ['x-y', 'omega-ruby-alpha-sapphire'],
    moveGroups: ['x-y', 'omega-ruby-alpha-sapphire'],
  },
  {
    label: 'Sun',
    value: 'sun',
    group: 'sun-moon',
    generation: 'Generation VII',
    genValue: 'generation-vii',
    genGroups: ['sun-moon', 'ultra-sun-ultra-moon', 'lets-go-pikachu-lets-go-eevee'],
    moveGroups: ['sun-moon', 'ultra-sun-ultra-moon'],
  },
  {
    label: 'Moon',
    value: 'moon',
    group: 'sun-moon',
    generation: 'Generation VII',
    genValue: 'generation-vii',
    genGroups: ['sun-moon', 'ultra-sun-ultra-moon', 'lets-go-pikachu-lets-go-eevee'],
    moveGroups: ['sun-moon', 'ultra-sun-ultra-moon'],
  },
  {
    label: 'Ultra Sun',
    value: 'ultra-sun',
    group: 'ultra-sun-ultra-moon',
    generation: 'Generation VII',
    genValue: 'generation-vii',
    genGroups: ['sun-moon', 'ultra-sun-ultra-moon', 'lets-go-pikachu-lets-go-eevee'],
    moveGroups: ['sun-moon', 'ultra-sun-ultra-moon'],
  },
  {
    label: 'Ultra Moon',
    value: 'ultra-moon',
    group: 'ultra-sun-ultra-moon',
    generation: 'Generation VII',
    genValue: 'generation-vii',
    genGroups: ['sun-moon', 'ultra-sun-ultra-moon', 'lets-go-pikachu-lets-go-eevee'],
    moveGroups: ['sun-moon', 'ultra-sun-ultra-moon'],
  },
  {
    label: 'Let\'s Go Pikachu',
    value: 'lets-go-pikachu',
    group: 'lets-go-pikachu-lets-go-eevee',
    generation: 'Generation VII',
    genValue: 'generation-vii',
    genGroups: ['sun-moon', 'ultra-sun-ultra-moon', 'lets-go-pikachu-lets-go-eevee'],
    moveGroups: ['lets-go-pikachu-lets-go-eevee'],
  },
  {
    label: 'Let\'s Go Eevee',
    value: 'lets-go-eevee',
    group: 'lets-go-pikachu-lets-go-eevee',
    generation: 'Generation VII',
    genValue: 'generation-vii',
    genGroups: ['sun-moon', 'ultra-sun-ultra-moon', 'lets-go-pikachu-lets-go-eevee'],
    moveGroups: ['lets-go-pikachu-lets-go-eevee'],
  },
  {
    label: 'Sword',
    value: 'sword',
    group: 'sword-shield',
    generation: 'Generation VIII',
    genValue: 'generation-viii',
    genGroups: ['sword-shield'],
    moveGroups: ['sword-shield'],
  },
  {
    label: 'Shield',
    value: 'shield',
    group: 'sword-shield',
    generation: 'Generation VIII',
    genValue: 'generation-viii',
    genGroups: ['sword-shield'],
    moveGroups: ['sword-shield'],
  },
  {
    label: 'Legends: Arceus',
    value: 'legends-arceus',
    group: 'scarlet-violet',
    generation: 'Generation VIII',
    genValue: 'generation-viii',
    genGroups: ['scarlet-violet'],
    moveGroups: ['scarlet-violet'],
  },
  {
    label: 'Scarlet',
    value: 'scarlet',
    group: 'scarlet-violet',
    generation: 'Generation IX',
    genValue: 'generation-ix',
    genGroups: ['scarlet-violet'],
    moveGroups: ['scarlet-violet'],
  },
  {
    label: 'Violet',
    value: 'violet',
    group: 'scarlet-violet',
    generation: 'Generation IX',
    genValue: 'generation-ix',
    genGroups: ['scarlet-violet'],
    moveGroups: ['scarlet-violet'],
  },
]