import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ReactNode } from 'react'
import { Header } from '@/components/layout/header/header'
import { Sidebar } from '@/components/layout/sidebar/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
    <body className={ `antialiased bg-gray-900 text-white ${ inter.className }` }>
      <div className="grid min-h-screen">
        <Header/>
        <Sidebar/>
        <main className="mt-20 h-auto bg-gray-900 px-4 pb-4 md:ml-64">
          { children }
        </main>
      </div>
    </body>
    </html>
  )
}
